// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBrowsers() {
  return window['go']['main']['App']['GetBrowsers']();
}

export function GetRandomCode() {
  return window['go']['main']['App']['GetRandomCode']();
}

export function OpenBrowser(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenBrowser'](arg1, arg2, arg3);
}

export function VerifyCode(arg1) {
  return window['go']['main']['App']['VerifyCode'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
