// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBrowsers():Promise<Array<Record<string, string>>>;

export function GetRandomCode():Promise<string>;

export function OpenBrowser(arg1:number,arg2:string,arg3:string):Promise<Record<string, any>>;

export function VerifyCode(arg1:string):Promise<Record<string, any>>;

export function WindowClose():Promise<void>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
